Relicense as Apache-2.0.
xmr-rs/portable-storage pull request #1
Opened 2020-11-26 10:14 UTC by jeandudey

2020-11-26 13:43 UTC, vorot93 requested changes

2020-11-26 13:43 UTC, vorot93 commented on README.md
> +<sup>Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech></sup>
```suggestion
<sup>Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech></sup>
<sup>Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me></sup>
```

2020-11-26 13:43 UTC, vorot93 commented on src/de.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-26 13:43 UTC, vorot93 commented on src/header.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-26 13:43 UTC, vorot93 commented on src/lib.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-26 13:43 UTC, vorot93 commented on src/raw_size.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-26 13:43 UTC, vorot93 commented on src/ser.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-26 13:43 UTC, vorot93 commented on utils/src/blob.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-26 13:43 UTC, vorot93 commented on utils/src/bytes_uuid.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-26 13:43 UTC, vorot93 commented on utils/src/lib.rs
> +// Copyright 2020 Jean Pierre Dudey <me@jeandudey.tech>
```suggestion
// Copyright 2018-2020 Jean Pierre Dudey <me@jeandudey.tech>
// Copyright 2020 Artem Vorotnikov <artem@vorotnikov.me>
```

2020-11-27 09:18 UTC, jeandudey commented
Changes applied

2020-11-27 10:15 UTC, vorot93 approved these changes

2020-11-27 10:16 UTC, merged